version: '3'
services:
  mysql57:
    image: mysql:8.0.29
    restart: unless-stopped
    container_name: poc_clean_architecture_api_mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - /home/bruno/dev/databases/volumes/mysql:/var/lib/mysql